#include "nrpc/generator.hpp"
#include <sstream>

namespace nrpc {

std::string CodeGenerator::generate_kotlin(const IRModule& ir) {
    std::ostringstream ss;
    ss << "// Generated by NRP Compiler (nrpc) v1.0.0 for Android ARM64\n";
    ss << "package " << (ir.classes.empty() ? "com.luasoup.nrp" : ir.classes.front().namespace_name) << "\n\n";

    for (const auto& cls : ir.classes) {
        ss << "class " << cls.name << " {\n";
        for (const auto& mth : cls.methods) {
            ss << "    external fun " << mth.name << "(";
            for (size_t i = 0; i < mth.parameters.size(); ++i) {
                if (i > 0) ss << ", ";
                ss << mth.parameters[i].name << ": " << mth.parameters[i].type.name;
            }
            ss << "): " << mth.return_type.name << "\n";
        }
        ss << "}\n\n";
    }

    return ss.str();
}

std::string CodeGenerator::generate_luau(const IRModule& ir) {
    std::ostringstream ss;
    ss << "-- Generated by NRP Compiler (nrpc) v1.0.0 for Android ARM64\n";
    ss << "local " << ir.name << " = {}\n\n";
    for (const auto& cls : ir.classes) {
        ss << "function " << ir.name << "." << cls.name << "()\n";
        ss << "    return {}\n";
        ss << "end\n\n";
    }
    ss << "return " << ir.name << "\n";
    return ss.str();
}

std::string CodeGenerator::generate_jni(const IRModule& ir) {
    std::ostringstream ss;
    ss << "// Generated JNI Bridge by NRP Compiler (Target ABI: " << ir.target_arch << ")\n";
    ss << "#include <jni.h>\n";
    ss << "#include \"nrp/core/runtime.hpp\"\n\n";
    ss << "// Module: " << ir.name << "\n";
    ss << "extern \"C\" JNIEXPORT jstring JNICALL\n";
    ss << "Java_com_luasoup_nrp_NRP_nativeGetTargetArch(JNIEnv* env, jclass clazz) {\n";
    ss << "    (void)env; (void)clazz;\n";
    ss << "    return env->NewStringUTF(\"" << ir.target_arch << "\");\n";
    ss << "}\n";
    return ss.str();
}

std::string CodeGenerator::generate_reflection(const IRModule& ir) {
    std::ostringstream ss;
    ss << "// Generated Reflection Descriptors for " << ir.name << "\n";
    ss << "#include \"nrp/reflection/registry.hpp\"\n";
    return ss.str();
}

std::string CodeGenerator::generate_docs(const IRModule& ir) {
    std::ostringstream ss;
    ss << "# Module API Documentation: " << ir.name << "\n\n";
    for (const auto& cls : ir.classes) {
        ss << "## Class `" << cls.name << "`\n";
    }
    return ss.str();
}

std::string CodeGenerator::generate_project_jni(const IRProject& proj) {
    std::ostringstream ss;
    ss << "// Auto-generated JNI Bridge for LuaSoup NRP (Android ARM64)\n";
    ss << "// Target ABI: " << proj.target_abi << "\n";
    ss << "#include <jni.h>\n";
    ss << "#include \"nrp/core/runtime.hpp\"\n";
    ss << "#include \"nrp/luau/luau_engine.hpp\"\n";
    ss << "#include \"nrp/modules/html.hpp\"\n";
    ss << "#include \"nrp/modules/json.hpp\"\n";
    ss << "#include \"nrp/modules/crypto.hpp\"\n\n";

    ss << "static nrp::Runtime g_runtime(\"android_arm64\");\n";
    ss << "static nrp::luau::LuauEngine g_luau;\n\n";

    ss << "extern \"C\" {\n\n";

    ss << "JNIEXPORT jstring JNICALL\n";
    ss << "Java_com_luasoup_nrp_NRP_nativeGetTargetArch(JNIEnv* env, jclass clazz) {\n";
    ss << "    (void)env; (void)clazz;\n";
    ss << "    return env->NewStringUTF(\"" << proj.target_abi << "\");\n";
    ss << "}\n\n";

    ss << "JNIEXPORT jboolean JNICALL\n";
    ss << "Java_com_luasoup_nrp_NRP_nativeInit(JNIEnv* env, jclass clazz) {\n";
    ss << "    (void)env; (void)clazz;\n";
    ss << "    g_runtime.initialize();\n";
    ss << "    g_luau.initialize();\n";
    ss << "    return JNI_TRUE;\n";
    ss << "}\n\n";

    ss << "JNIEXPORT jstring JNICALL\n";
    ss << "Java_com_luasoup_nrp_NRP_nativeEvalLuau(JNIEnv* env, jclass clazz, jstring jscript) {\n";
    ss << "    (void)clazz;\n";
    ss << "    const char* script = env->GetStringUTFChars(jscript, nullptr);\n";
    ss << "    auto res = g_luau.eval(script ? script : \"\");\n";
    ss << "    if (script) env->ReleaseStringUTFChars(jscript, script);\n";
    ss << "    std::string out = res.is_string() ? res.as_string() : \"OK\";\n";
    ss << "    return env->NewStringUTF(out.c_str());\n";
    ss << "}\n\n";

    ss << "JNIEXPORT jstring JNICALL\n";
    ss << "Java_com_luasoup_nrp_NRP_nativeParseHTML(JNIEnv* env, jclass clazz, jstring jhtml) {\n";
    ss << "    (void)clazz;\n";
    ss << "    const char* html = env->GetStringUTFChars(jhtml, nullptr);\n";
    ss << "    auto doc = nrp::modules::html::Document::parse(html ? html : \"\");\n";
    ss << "    if (html) env->ReleaseStringUTFChars(jhtml, html);\n";
    ss << "    return env->NewStringUTF(doc->outer_html().c_str());\n";
    ss << "}\n\n";

    ss << "} // extern \"C\"\n";
    return ss.str();
}

std::string CodeGenerator::generate_project_kotlin(const IRProject& proj) {
    std::ostringstream ss;
    ss << "// Auto-generated Android Kotlin SDK for " << proj.name << "\n";
    ss << "package com.luasoup.nrp\n\n";
    ss << "object GeneratedNRPBridge {\n";
    ss << "    const val TARGET_ABI: String = \"" << proj.target_abi << "\"\n";
    ss << "    const val TOTAL_MODULES: Int = " << proj.modules.size() << "\n";
    ss << "}\n";
    return ss.str();
}

std::string CodeGenerator::generate_project_reflection(const IRProject& proj) {
    std::ostringstream ss;
    ss << "// Auto-generated Reflection Metadata Registry Descriptors\n";
    ss << "#include \"nrp/reflection/registry.hpp\"\n\n";
    ss << "namespace nrp::generated {\n";
    ss << "void register_all_metadata() {\n";
    ss << "    auto& reg = nrp::ReflectionRegistry::instance();\n";
    for (const auto& [name, mod] : proj.modules) {
        ss << "    reg.register_class({\"" << name << "\", \"" << mod.id << "\", \"\", {}, {}, \"Specification module\"});\n";
    }
    ss << "}\n";
    ss << "} // namespace nrp::generated\n";
    return ss.str();
}

std::string CodeGenerator::generate_project_summary(const IRProject& proj) {
    std::ostringstream ss;
    ss << "=== LuaSoup NRP Compiler Summary ===\n";
    ss << "Project: " << proj.name << "\n";
    ss << "Target ABI: " << proj.target_abi << "\n";
    ss << "Total Specification Modules Parsed: " << proj.modules.size() << "\n";
    return ss.str();
}

} // namespace nrpc
